### ISSUE TITLE
Fix issue of " label " duplication

### ISSUE THREAD

**Issue by hnabaheen** [KrishnaPatell/KPDropMenu#2]
Hi @KrishnaPatell .. 
this will fix an issue appear when you set  title for the drop menu .
in **KPDropMenu.m**
 before adding " label " to subviews check if its added before or not by placing the label initialization between this 
```
if (label == null ){
}
```
and the same way with " tblView "

for more flexibility let the developer set the initial selected item .

**Comment by rajdhakate** [comment]
@hm4n Hey. can you elaborate a little. what do you mean by "and the same way with " tblView "

**Comment by KrishnaPatell** [comment]
Please elaborate your problem.. @hm4n

**Comment by hnabaheen** [comment]
@KrishnaPatell ..
The problem appear when you set default title .. it solved as I mentioned above 👍
