### ISSUE TITLE
KPDropDown inside UItableView Cell - didSelectItem not called

### ISSUE THREAD

**Issue by rajdhakate** [KrishnaPatell/KPDropMenu#4]
Hi,
I've placed KPDropDown menu inside 3 cells of my UItableView. I've set the delegates to self (my view controller). 

I can confirm that `didShow` and `didHide` methods are called when showing and hiding the drop menu. 
But `didSelectItem` method is not called. Instead control below that drop menu is getting selected.

What could be the problem?

**Comment by hoanglinhkd** [comment]
Change this code:
-(void)didTap : (id)sender {
    isCollapsed = !isCollapsed;
    if(!isCollapsed) {
        CGFloat height = (CGFloat)(_items.count > 5 ? _itemHeight*5 : _itemHeight * (double)(_items.count));
        
        tblView.layer.zPosition = 1;
        [tblView removeFromSuperview];
        tblView.layer.borderColor = [[UIColor lightGrayColor] CGColor];
        tblView.layer.borderWidth = 1;
        tblView.layer.cornerRadius = 4;
        [[self.superview superview] addSubview:tblView]; // go to superview that can show tableview in it's frame.
        [tblView reloadData];
        
        [UIView animateWithDuration:0.25 animations:^{
            
            if(_DirectionDown)
                tblView.frame = CGRectMake(self.frame.origin.x + self.superview.frame.origin.x, self.frame.origin.y + self.superview.frame.origin.y + self.frame.size.height+5, self.frame.size.width, height);
            else
                tblView.frame = CGRectMake(self.frame.origin.x + self.superview.frame.origin.x, self.frame.origin.y + self.superview.frame.origin.y - 5 - height, self.frame.size.width, height);
        }];
        
        if(_delegate != nil){
            [_delegate didShow:self];
        }
        
        UIView *view = [[UIView alloc] initWithFrame:[UIScreen mainScreen].bounds];
        view.tag = 99121;
        [self.superview insertSubview:view belowSubview:tblView];
        
    }
    else{
        [self collapseTableView];
    }
}

**Comment by hoanglinhkd** [comment]
I fixed this issues in attachment file.
[KPDropMenu.zip](https://github.com/KrishnaPatell/KPDropMenu/files/960647/KPDropMenu.zip)
